# -*- coding: utf-8 -*-
"""Сольська_DA6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rgUCFnze05Jhx56as6ZMb_iCQvNeMLcU

##<center>__Самостійні завдання__</center>

> Скопіювати блок самостійних завдань в окремий файл ***LastName_DA6.py***

> Інсталюйте необхідні пакети бібліотек Python збережіть у файл `requirements.txt`

> завантажте файл зі статистичного банку даних, з яким будете працювати `data.csv`

### Завдання

1. Створіть dashboard, як додаток у **Streamlit Community Cloud**
2. Додаток має містити: панель фільтрації з елементами
- Заголовок      
- Текстовий опис / інструкції                       
- Один вибір зі списку                              
- Кілька виборів                                   
- Вибір одного варіанту з декількох (радіо-кнопки)  
- Прапорець        
3. В головній частині: таблиця, як результат фільтрів з можливістю вибору колонок
4. Графічне представлення (мінімум 3 типи графіки)
5. Реалізація регресійної моделі або інших (кластеризації/класифікації)                        
6. Створені файли мають бути розміщені в репрозиторії GitHub, та імплементуватися в Streamlit Community Cloud
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans

st.set_page_config(
    page_title="Економічний дашборд компаній",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        'Get Help': 'https://docs.streamlit.io/',
        'Report a bug': 'https://github.com/streamlit/streamlit/issues',
        'About': 'Інтерактивна панель для економічного аналізу підприємств'
    }
)

@st.cache_data
def load_data():
    try:
        df = pd.read_csv('streamlit_dataset.csv')
        return df
    except FileNotFoundError:
        st.error("Файл `streamlit_dataset.csv` не знайдено. Завантажте його в корінь репозиторію.")
        st.stop()

df = load_data()

st.sidebar.title("🛠 Панель фільтрації")

# Фільтри
selected_year = st.sidebar.selectbox("Рік", sorted(df["Year"].unique()))

selected_region = st.sidebar.multiselect(
    "Регіон",
    options=df["Region"].unique(),
    default=df["Region"].unique()
)

selected_industry = st.sidebar.multiselect(
    "Галузь",
    options=df["Industry"].unique(),
    default=df["Industry"].unique()
)

selected_scenario = st.sidebar.radio("Сценарій", df["Scenario"].unique())

selected_max_adbudget = st.sidebar.slider(
    "Максимальний рекламний бюджет",
    min_value=int(df["AdBudget"].min()),
    max_value=int(df["AdBudget"].max()),
    value=int(df["AdBudget"].max()),
    step=1000
)

show_map = st.sidebar.checkbox("🗺 Показати карту компаній", value=True)

# Вибір типу графіка
chart_option = st.sidebar.radio(
    "📈 Оберіть графік для перегляду:",
    [
        "Доходи на клієнта vs Витрати",
        "Boxplot прибутку по галузях",
        "Scatter: Прибуток vs Інвестиції",
        "Гістограма конверсії по галузях",
        "Теплова карта кореляцій",
        "Кластеризація компаній (KMeans)"
    ]
)

# Блок регресії (після фільтрації, тому нижче)
st.sidebar.markdown("---")
st.sidebar.markdown("**Побудова лінійної регресії**")

df_filtered = df[
    (df["Year"] == selected_year) &
    (df["Region"].isin(selected_region)) &
    (df["Industry"].isin(selected_industry)) &
    (df["Scenario"] == selected_scenario) &
    (df["AdBudget"] <= selected_max_adbudget)
]

st.title("📊 Економічний дашборд компаній")
st.subheader(f"🔍 Відфільтровано **{df_filtered.shape[0]}** компаній")

# Кнопка завантаження CSV
if not df_filtered.empty:
    csv = df_filtered.to_csv(index=False).encode("utf-8")
    st.download_button(
        label="⬇️ Завантажити відфільтровані дані (CSV)",
        data=csv,
        file_name=f"filtered_companies_{selected_year}.csv",
        mime="text/csv"
    )

# Вибір колонок для таблиці
st.subheader("📋 Таблиця результатів")
all_columns = df_filtered.columns.tolist()
default_columns = ["Company", "Region", "Industry", "Profit", "ROI", "AdBudget"]
selected_columns = st.multiselect(
    "Оберіть стовпці для відображення",
    options=all_columns,
    default=[col for col in default_columns if col in all_columns]
)

if selected_columns:
    st.dataframe(df_filtered[selected_columns], use_container_width=True)
else:
    st.info("Оберіть хоча б один стовпець")

# Карта компаній
if show_map:
    st.subheader("🗺 Географія компаній")
    map_data = df_filtered[["Latitude", "Longitude"]].dropna().rename(
        columns={"Latitude": "latitude", "Longitude": "longitude"}
    )
    if not map_data.empty:
        st.map(map_data)
    else:
        st.warning("Немає даних з координатами для обраних фільтрів.")

st.subheader("📈 Візуалізація даних")

if chart_option == "Доходи на клієнта vs Витрати":
    st.subheader("Доходи на клієнта vs Витрати")
    if not df_filtered.empty:
        chart = alt.Chart(df_filtered).mark_circle(size=60).encode(
            x="Expenses:Q",
            y="RevenuePerCustomer:Q",
            color="Industry:N",
            tooltip=["Company", "Expenses", "RevenuePerCustomer", "Industry"]
        ).interactive().properties(title="Доходи на клієнта vs Витрати")
        st.altair_chart(chart, use_container_width=True)
    else:
        st.warning("Немає даних для графіка.")

elif chart_option == "Boxplot прибутку по галузях":
    st.subheader("Boxplot прибутку по галузях")
    if not df_filtered.empty:
        fig, ax = plt.subplots(figsize=(10, 6))
        sns.boxplot(data=df_filtered, x="Industry", y="Profit", ax=ax)
        ax.set_title("Розподіл прибутку по галузях")
        ax.tick_params(axis='x', rotation=45)
        st.pyplot(fig)
    else:
        st.warning("Немає даних.")

elif chart_option == "Scatter: Прибуток vs Інвестиції":
    st.subheader("Прибуток vs Інвестиції")
    if not df_filtered.empty:
        chart = alt.Chart(df_filtered).mark_circle(size=60).encode(
            x="Investment:Q",
            y="Profit:Q",
            color="Industry:N",
            tooltip=["Company", "Investment", "Profit", "Industry"]
        ).interactive()
        st.altair_chart(chart, use_container_width=True)
    else:
        st.warning("Немає даних.")

elif chart_option == "Гістограма конверсії по галузях":
    st.subheader("Середній Conversion Rate по галузях")
    if not df_filtered.empty:
        fig, ax = plt.subplots(figsize=(10, 6))
        sns.barplot(data=df_filtered, x="Industry", y="ConversionRate", estimator="mean", ax=ax)
        ax.set_title("Середній рівень конверсії по галузях")
        ax.tick_params(axis='x', rotation=45)
        st.pyplot(fig)
    else:
        st.warning("Немає даних.")

elif chart_option == "Теплова карта кореляцій":
    st.subheader("Теплова карта кореляцій")
    numeric_cols = df_filtered.select_dtypes(include=[np.number])
    if not numeric_cols.empty:
        corr = numeric_cols.corr()
        fig, ax = plt.subplots(figsize=(10, 8))
        sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f", ax=ax)
        ax.set_title("Кореляційна матриця числових показників")
        st.pyplot(fig)
    else:
        st.warning("Немає числових даних для кореляції.")

elif chart_option == "Кластеризація компаній (KMeans)":
    st.subheader("Кластеризація компаній за ROI та Investment")
    cluster_data = df_filtered[["ROI", "Investment"]].dropna().copy()
    if cluster_data.shape[0] >= 3:
        kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
        cluster_data["Cluster"] = kmeans.fit_predict(cluster_data)

        chart = alt.Chart(cluster_data).mark_circle(size=70).encode(
            x="Investment:Q",
            y="ROI:Q",
            color="Cluster:N",
            tooltip=["ROI", "Investment", "Cluster"]
        ).interactive().properties(title="Кластеризація компаній (KMeans)")
        st.altair_chart(chart, use_container_width=True)
    else:
        st.warning("Недостатньо даних для кластеризації (потрібно мінімум 3 рядки).")

numeric_columns = df_filtered.select_dtypes(include=np.number).columns.tolist()

if numeric_columns:
    reg_x = st.sidebar.selectbox("Оберіть незалежну змінну (X)", numeric_columns, index=0)
    reg_y = st.sidebar.selectbox("Оберіть залежну змінну (Y)", numeric_columns, index=min(1, len(numeric_columns)-1))
    show_regression = st.sidebar.checkbox("Показати лінійну регресію", value=False)

    if show_regression:
        st.subheader(f"📈 Лінійна регресія: {reg_y} ~ {reg_x}")
        df_reg = df_filtered[[reg_x, reg_y]].dropna()

        if df_reg.shape[0] >= 2:
            model = LinearRegression()
            model.fit(df_reg[[reg_x]], df_reg[reg_y])
            y_pred = model.predict(df_reg[[reg_x]])

            coef = model.coef_[0]
            intercept = model.intercept_
            r2 = model.score(df_reg[[reg_x]], df_reg[reg_y])

            st.markdown(f"**Коефіцієнт нахилу (β):** {coef:.4f}")
            st.markdown(f"**Зсув (intercept):** {intercept:.4f}")
            st.markdown(f"**Коефіцієнт детермінації R²:** {r2:.4f}")

            fig, ax = plt.subplots(figsize=(9, 6))
            sns.scatterplot(data=df_reg, x=reg_x, y=reg_y, ax=ax, label="Дані")
            sns.lineplot(x=df_reg[reg_x], y=y_pred, color='red', ax=ax, label="Регресійна лінія")
            ax.set_title(f"Регресія: {reg_y} від {reg_x}")
            ax.legend()
            st.pyplot(fig)
        else:
            st.warning("Недостатньо даних для побудови регресії (потрібно ≥ 2 рядки).")
else:
    st.sidebar.info("Немає числових колонок для регресії після фільтрації.")

# Інструкція в sidebar
st.sidebar.markdown("---")
st.sidebar.markdown("""
**Інструкція:**
- Оберіть рік, регіони, галузі та сценарій
- Обмежте рекламний бюджет слайдером
- Виберіть тип графіка
- Для регресії оберіть змінні X та Y
""")
st.sidebar.markdown("**Автор:** Вікторія")

